#!/usr/bin/env python3
# PATCHED
# Date: 2025-07-21
# Task: Patched DB instantiation and SQL syntax for PostgreSQL.
# Source: uploaded:feature_scorecard.py

import numpy as np
import pandas as pd
import json
import logging
from pathlib import Path
from .feature_registry import FeatureRegistry
from .feature_validator import FeatureValidator

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger('FeatureScorecard')

class FeatureScorecard:
    def __init__(self, registry: FeatureRegistry, validator: FeatureValidator):
        self.registry = registry
        self.validator = validator
        logger.info("Feature scorecard initialized")

    def detect_decay(self, feature_id):
        # Using %s placeholder for psycopg2
        self.registry.cursor.execute(
            "SELECT metrics, validation_date FROM feature_performance WHERE feature_id = %s ORDER BY validation_date DESC LIMIT 2",
            (feature_id,)
        )
        results = self.registry.cursor.fetchall()
        if len(results) < 2:
            return False

        current_metrics = results[0][0] # JSONB is already a dict
        previous_metrics = results[1][0]

        ic_current = current_metrics.get('information_coefficient', 0)
        ic_previous = previous_metrics.get('information_coefficient', 0)
        
        if ic_previous == 0: return False

        decay = (ic_previous - ic_current) / abs(ic_previous)
        return decay > 0.3

    def run_scorecard(self):
        logger.info("Running periodic performance review")
        self.validator.validate_features(status='testing')
        self.validator.validate_features(status='live')

        self.registry.cursor.execute("SELECT id FROM features WHERE status = 'live'")
        live_features = self.registry.cursor.fetchall()

        for (feature_id,) in live_features:
            if self.detect_decay(feature_id):
                self.registry.update_feature_status(feature_id, 'decaying')
                logger.warning(f"Feature {feature_id} marked as decaying")

def deploy_live_features(registry: FeatureRegistry, output_path="feature_factory/deployed_features.py"):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Generating deployment script: {output_path}")
    live_features = registry.get_live_features_code()

    # The header and function templates remain the same
    header = """# AUTO-GENERATED FEATURE DEPLOYMENT
# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated by feature_scorecard.py
import pandas as pd
import numpy as np

"""
    apply_all_header = """
def apply_all_features(df: pd.DataFrame) -> pd.DataFrame:
    \"\"\"
    Apply all live features to the dataframe.
    This function is auto-generated.
    \"\"\"
"""
    function_definitions = []
    function_calls = []

    for name, code_logic in live_features:
        func_name = name.lower().replace(' ', '_')
        # Create a self-contained function for each feature
        func_def = f"def _{func_name}(df_in: pd.DataFrame) -> pd.Series:\n    # Feature: {name}\n    df = df_in.copy()\n    {code_logic.replace(chr(10), chr(10) + '    ')}\n    return df['{name}']\n"
        function_definitions.append(func_def)
        function_calls.append(f"    df['{name}'] = _{func_name}(df)")

    footer = f"\n    return df\n\n# Generated on: {pd.Timestamp.now()}\n# Total features: {len(live_features)}"

    with open(output_path, 'w') as f:
        f.write(header)
        f.write('\n'.join(function_definitions))
        f.write(apply_all_header)
        f.write('\n'.join(function_calls))
        f.write(footer)

    logger.info(f"Deployed {len(live_features)} features to {output_path}")

if __name__ == '__main__':
    db_connection_params = {
        "dbname": "cta_db", "user": "postgre", "password": "a",
        "host": "localhost", "port": "5432"
    }
    registry = None
    try:
        registry = FeatureRegistry(db_params=db_connection_params)
        validator = FeatureValidator(registry)
        scorecard = FeatureScorecard(registry, validator)
        scorecard.run_scorecard()
        deploy_live_features(registry)
    except Exception as e:
        logger.error(f"An error occurred: {e}")
    finally:
        if registry:
            registry.close()